import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";

const geistSans = localFont({
  src: "./fonts/Satoshi-Black.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Satoshi-Black.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className="flex-1 bg-gray-100">
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
